### PR TITLE
Module 5 Markdown conversion

### PR DESCRIPTION
**Pull request by jjpendlebury**
Module 5 document changed to a markdown file as per Nick's instructions.

### CODE REVIEW

**Review by MarkA21 — CHANGES_REQUESTED** [review]
Looks good - thanks for the submission. If you could add the links to the table of contents like in Nick's example that would be great and then I will merge it.

**Comment by jjpendlebury** [comment]
I understand, will do!

**Comment by jjpendlebury** [comment]
Should be all ready to merge now, I've added the ToC links to the bottom.

**Review by MarkA21 — APPROVED** [review]
Thanks very much. Looks good!

**Pull request merged**
